/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertemuan17May23;

/**
 *
 * @author ACER
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        pinSalah.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lanjutkan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pinSalah = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(null);

        jPanel2.setBackground(java.awt.Color.blue);
        jPanel2.setMaximumSize(new java.awt.Dimension(1024, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel2.setLayout(null);

        jButton1.setBackground(java.awt.Color.blue);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 11, 61, 23);

        lanjutkan.setBackground(java.awt.Color.blue);
        lanjutkan.setForeground(java.awt.Color.white);
        lanjutkan.setText("Lanjutkan");
        lanjutkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutkanActionPerformed(evt);
            }
        });
        jPanel2.add(lanjutkan);
        lanjutkan.setBounds(930, 10, 79, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Masukkan PIN Anda");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(360, 120, 240, 29);

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setMinimumSize(new java.awt.Dimension(150, 23));
        txtPassword.setPreferredSize(new java.awt.Dimension(150, 42));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(400, 170, 150, 42);

        pinSalah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pinSalah.setForeground(java.awt.Color.red);
        pinSalah.setText("PIN anda salah!!");
        jPanel2.add(pinSalah);
        pinSalah.setBounds(400, 230, 150, 22);
        pinSalah.getAccessibleContext().setAccessibleName("pinSalah");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1024, 600);

        setBounds(0, 0, 1040, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutkanActionPerformed
        pinModel pin_ = new pinModel();
        
        if (txtPassword.getText().equals(pin_.getPin())){
            new halamanUtama().setVisible(true);
            this.setVisible(false);
        }
        else{
            pinSalah.setVisible(true);
            txtPassword.setText("");
        }
    }//GEN-LAST:event_lanjutkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lanjutkan;
    private javax.swing.JLabel pinSalah;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
