/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertemuan17May23;

/**
 *
 * @author ACER
 */
public class transfer extends javax.swing.JFrame {

    /**
     * Creates new form transfer
     */
    public transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radSBank = new javax.swing.JRadioButton();
        radABank = new javax.swing.JRadioButton();
        txtRek = new javax.swing.JTextField();
        txtNominal = new javax.swing.JTextField();
        btnKirim = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxRincian = new javax.swing.JTextArea();
        btnSelesai = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.blue);
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Rekening");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Transfer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 90, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Rekening");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 80, 15);

        radSBank.setBackground(java.awt.Color.blue);
        radSBank.setForeground(new java.awt.Color(255, 255, 255));
        radSBank.setText("Sesama Bank");
        jPanel1.add(radSBank);
        radSBank.setBounds(110, 90, 120, 23);

        radABank.setBackground(java.awt.Color.blue);
        radABank.setForeground(new java.awt.Color(255, 255, 255));
        radABank.setText("Antar Bank");
        jPanel1.add(radABank);
        radABank.setBounds(110, 120, 110, 23);
        jPanel1.add(txtRek);
        txtRek.setBounds(110, 10, 100, 30);
        jPanel1.add(txtNominal);
        txtNominal.setBounds(110, 50, 100, 30);

        btnKirim.setBackground(java.awt.Color.blue);
        btnKirim.setForeground(new java.awt.Color(255, 255, 255));
        btnKirim.setText("Kirim");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });
        jPanel1.add(btnKirim);
        btnKirim.setBounds(110, 160, 70, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rincian Transaksi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 190, 110, 14);

        boxRincian.setColumns(20);
        boxRincian.setRows(5);
        jScrollPane1.setViewportView(boxRincian);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 180, 96);

        btnSelesai.setBackground(java.awt.Color.blue);
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelesai);
        btnSelesai.setBounds(10, 330, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        transferModel tf = new transferModel();
        informasiSaldoModel saldo = new informasiSaldoModel();
        
        tf.setNoRek(txtRek.getText());        
        tf.setjTransfer(Integer.parseInt(txtNominal.getText()));
        
        if(radSBank.isSelected()){
            int sisa = saldo.getDuit()-tf.getjTransfer();
            saldo.setDuit(sisa);
            boxRincian.setText("Nomor Rekening: "+tf.getNoRek()+
                    "\nJumlah Transfer: "+tf.getjTransfer()+
                    "\nSisa Saldo: "+Integer.toString(sisa)
                    );
        }
        
        if (radABank.isSelected()){
            int sisa = saldo.getDuit()-tf.getjTransfer()-5000;
            saldo.setDuit(sisa);

            boxRincian.setText("Nomor Rekening: "+tf.getNoRek()+
                    "\nJumlah Transfer: Rp."+tf.getjTransfer()+
                    "\nBiaya Admin: Rp.5000"+
                    "\nSisa Saldo: Rp."+Integer.toString(sisa)
                    );
        }
    }//GEN-LAST:event_btnKirimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea boxRincian;
    private javax.swing.JButton btnKirim;
    private javax.swing.JButton btnSelesai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radABank;
    private javax.swing.JRadioButton radSBank;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtRek;
    // End of variables declaration//GEN-END:variables
}
